#!/bin/bash
#
#  add-gpl is free software; you can redistribute it and/or modify it under the
#  terms of the GNU General Public License as published by the Free Software
#  Foundation; either version 2 of the License, or any later version.
#
#  add-gpl is distributed in the hope that it will be useful, but WITHOUT ANY
#  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
#  A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along with
#  this program; if not, write to the Free Software Foundation, Inc., 59 Temple
#  Place - Suite 330, Boston, MA 02111-1307, USA
#
# This script should be used to add a license in scripts.
#

script="SlackBuild"
#script="build"

for file in `find -name "*.$script"`; do

  echo Changing $file...
  package="`basename $file .$script`"
  slackbuild="`basename $file`"

  string="\#\!\/bin\/bash\n\#\n#  $slackbuild is free software; you can redistribute it and\/or modify it under the\n#  terms of the GNU General Public License as published by the Free Software\n#  Foundation; either version 2 of the License, or any later version.\n#\n#  $slackbuild is distributed in the hope that it will be useful, but WITHOUT ANY\n#  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR\n#  A PARTICULAR PURPOSE.  See the GNU General Public License for more details.\n#\n#  You should have received a copy of the GNU General Public License along with\n#  this program; if not, write to the Free Software Foundation, Inc., 59 Temple\n#  Place - Suite 330, Boston, MA 02111-1307, USA"

  sed -e "s/\#\!\/bin\/bash/$string/" $file > $file.new
  cat $file.new > $file
  rm $file.new

done
