#!/bin/bash
#
#  This software is free software; you can redistribute it and/or modify it under the
#  terms of the GNU General Public License as published by the Free Software
#  Foundation; either version 2 of the License, or any later version.
#
#  This software is distributed in the hope that it will be useful, but WITHOUT ANY
#  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
#  A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along with
#  this program; if not, write to the Free Software Foundation, Inc., 59 Temple
#  Place - Suite 330, Boston, MA 02111-1307, USA
#
# script for converting simplepkg templates
# to the 0.5 own-folder format
#

cwd="/etc/simplepkg"
cd $cwd

for file in `ls *.template`; do
  cd $cwd  
  template="`echo $file | cut -d . -f 1`"
  mkdir templates/$template
  mv $template.d templates/$template/
  mv $template.s templates/$templates/
  mv $template.template templates/$template/
  cd templates/$template/$template.s
  # optional step
  # if [ "$template" != "vserver" ]; then
  #   ln -sf ../../../defaults/templatesvserver/vserver.s/vserver.sh
  # fi
done

