#!/bin/bash
#
#  This software is free software; you can redistribute it and/or modify it under the
#  terms of the GNU General Public License as published by the Free Software
#  Foundation; either version 2 of the License, or any later version.
#
#  This software is distributed in the hope that it will be useful, but WITHOUT ANY
#  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
#  A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along with
#  this program; if not, write to the Free Software Foundation, Inc., 59 Temple
#  Place - Suite 330, Boston, MA 02111-1307, USA
#
# tip: to assemble a template from all slack tagfiles:
#
# for diskset in a ap d e f k l n t tcl x xap y; do 
#   lynx -dump http://url/to/slackware/$diskset/tagfile >> slack.template
# done
#

if [ -z "$2" ]; then
  echo "usage: `basename $0` <template> <base-template>"
  exit 1
elif [ ! -f "$1" ] || [ ! -f "$2" ]; then
  echo error: $1 ou $2 not found
  exit 1
fi

cp $2 $1.new

cat $1 | while read line; do
  pack="`echo $line | cut -d : -f 1`"
  if ! grep -qe "^$pack:" $2; then
    echo $line >> $1.new
  fi
done
